const YELP_API_KEY = process.env.YELP_API_KEY;
const YELPERHELPER_NODE_ADDRESS = process.env.YELPERHELPER_NODE_ADDRESS;
const YELPERHELPER_SPRING_ADDRESS = process.env.YELPERHELPER_SPRING_ADDRESS;

module.exports = {
  YELP_API_KEY: YELP_API_KEY,
  YELPERHELPER_NODE_ADDRESS: YELPERHELPER_NODE_ADDRESS,
  YELPERHELPER_SPRING_ADDRESS: YELPERHELPER_SPRING_ADDRESS,
}